## Put comments here that give an overall description of what your
## functions do


## Write a short comment describing this function

#JLW: makeCacheMatrix returns. a list of functions that can store a matrix in a 
# cache as well as it's inverse on calculation with solve

makeCacheMatrix <- function(x = matrix()) {
  m <- NULL
  set <- function(y) {
      x <<- y
      m <<- NULL
  }
  get <- function() x
  setInverse <- function(solve) m <<- solve
  getInverse <-  function() m
  list(set = set, get = get, setInverse=setInverse, getInverse=getInverse)

}


## Write a short comment describing this function

#JLW: When passed the vector of functions generated by makeCacheMatrix, returnes
# the inverse of the matrix from cache if available or solves it and stores it
# in cache

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
  m <- x$getInverse()
  if(!is.null(m)){
    message("getting cached data")
    return(m)
  }
  data <-  x$get()
  m <- solve(data,...)
  x$setInverse(m)
  m
}
